<script>
    let searchTerm = '';
    let promise;
    let src = '';
    $: if (searchTerm != '') {
        promise = getPhoto();
    }
    
    async function getPhoto() {
        let thisSearchTerm = searchTerm;
        const res = await fetch(`https://source.unsplash.com/featured/1600x900/?${searchTerm}`);
        let photoUrl = res.url;
        if (res.ok && thisSearchTerm == searchTerm) {
            src = photoUrl;
        }
    }
  </script>
  <input type="text" placeholder="dog, car, house" bind:value={searchTerm} />
  <img {src} alt="An image generated by searching for {searchTerm}." class:invisible={!src} />
  {#await promise}
    <div class="loading"><img src="/loading.gif" alt="Loading..."></div>
  {/await}